import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // include the weights you need
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light ">
      <body
        className={`${workSans.variable} ${workSans.className} ${geistMono.variable} antialiased bg-background-light text-foreground-light dark:text-foreground-dark dark:bg-background-dark transition-colors duration-200 ease-out`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
